<?php

namespace Database\Seeders;

use App\Models\Link;
use App\Models\User;
use App\Models\Section;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LinksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $links = [
            [
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'link_name' => 'Badan Pusat Statistik',
                'instansi' => 'BPS',
                'url' => 'https://bps.go.id',
                'description_link' => 'Website Utama Badan Pusat Statistik Republik Indonesia',
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Pengolahan')->first()->id,
                'link_name' => 'Fasih SM',
                'instansi' => 'BPS',
                'url' => 'https://fasih-sm.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'link_name' => 'BPS Kota Solok',
                'instansi' => 'BPS',
                'url' => 'https://solokkota.bps.go.id',
                'description_link' => null,
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'link_name' => 'lms.bps.go.id',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://lms.bps.go.id',
                'description_link' => null,
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Seruti',
                'instansi' => 'BPS',
                'url' => 'https://webapps.bps.go.id/olah/seruti/login',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengolahan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Sistem Akuntansi dan Pelaporan Keuangan (SAKTI)',
                'instansi' => 'Kemenkeu',
                'url' => 'https://sakti.kemenkeu.go.id/',
                'description_link' => 'Pengelolaan keuangan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'SPANINT',
                'instansi' => 'Kemenkeu',
                'url' => 'https://spanint.kemenkeu.go.id/',
                'description_link' => 'Pengelolaan keuangan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Satu DJA',
                'instansi' => 'Kemenkeu',
                'url' => 'https://satudja.kemenkeu.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Backoffice BPS',
                'instansi' => 'BPS',
                'url' => 'https://backoffice.bps.go.id',
                'description_link' => null,
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Mailhost BPS',
                'instansi' => 'BPS',
                'url' => 'https://mailhost.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Pusdiklat BPS',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://pusdiklat.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Webmonitoring BPS',
                'instansi' => 'BPS',
                'url' => 'https://webmonitoring.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'SIRUP LKPP',
                'instansi' => 'LKP',
                'url' => 'https://sirup.lkpp.go.id/sirup/loginctr/index',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'LPSE BPS',
                'instansi' => 'BPS',
                'url' => 'https://lpse.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Romantik BPS',
                'instansi' => 'BPS',
                'url' => 'https://romantik.web.bps.go.id/',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'PST BPS',
                'instansi' => 'BPS',
                'url' => 'https://pst.bps.go.id/login',
                'description_link' => null,
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Dashboard BPS',
                'instansi' => 'BPS',
                'url' => 'https://dashboard.bps.go.id/',
                'description_link' => 'Dashboard Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Fasih Dashboard',
                'instansi' => 'BPS',
                'url' => 'https://fasih-dashboard.bps.go.id/login/',
                'description_link' => 'Dashboard Fasih',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'E-Learning BPS',
                'instansi' => 'BPS',
                'url' => 'https://elearning.bps.go.id/',
                'description_link' => 'E-Learning Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Community BPS',
                'instansi' => 'BPS',
                'url' => 'https://community.bps.go.id/',
                'description_link' => 'Community Badan Pusat Statistik',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Manajemen Mitra BPS',
                'instansi' => 'BPS',
                'url' => 'https://manajemen-mitra.bps.go.id/',
                'description_link' => 'Manajemen Mitra Badan Pusat Statistik',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SIPMEN BPS',
                'instansi' => 'BPS',
                'url' => 'https://simdiklat.web.bps.go.id/',
                'description_link' => 'Sistem Informasi Pengembangan Manajemen',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Data Spasial BPS',
                'instansi' => 'BPS',
                'url' => 'https://dataspasial.bps.go.id/index/',
                'description_link' => 'Data Spasial Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'FRS BPS',
                'instansi' => 'BPS',
                'url' => 'https://frs.bps.go.id/area/login',
                'description_link' => 'Framework Repository System',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Penyusunan Laporan Keuangan Satker',
                'instansi' => 'Kemenkeu',
                'url' => 'https://akuntansi.bps.go.id/ecalkv2/web/site/login',
                'description_link' => 'Penyusun Laporan Keuangan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Layanan Online Kementerian Keuangan',
                'instansi' => 'Kemenkeu',
                'url' => 'https://spanint.kemenkeu.go.id/spanint/latest/app/',
                'description_link' => 'Monitoring Transaksi SPAN',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'DIGIT',
                'instansi' => 'Kemenkeu',
                'url' => 'https://digit.kemenkeu.go.id/login#/',
                'description_link' => 'Akses Antar Layanan Digital Dirjen Perbendaharaan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'djp',
                'instansi' => 'Kemenkeu',
                'url' => 'https://djponline.pajak.go.id/account/login',
                'description_link' => 'Pembuatan Billing Setor dan Pelaporan Pajak',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Monitoring Sistem Aplikasi Keuangan oleh Pengguna Aplikasi Sakti',
                'instansi' => 'Kemenkeu',
                'url' => 'https://monsakti.kemenkeu.go.id/dist/app/',
                'description_link' => 'Monitoring Sistem Aplikasi Keuangan oleh Pengguna Aplikasi Sakti',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Informasi Kepegawaian',
                'instansi' => 'BPS',
                'url' => 'https://simpeg.bps.go.id',
                'description_link' => 'Sistem Informasi Kepegawaian',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Pengambilan Cuti',
                'instansi' => 'BPS',
                'url' => 'https://sipecut.bps.go.id',
                'description_link' => 'Sistem Pengambilan Cuti',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'KIP',
                'instansi' => 'BPS',
                'url' => 'https://webapps.bps.go.id/kipapp',
                'description_link' => 'KIP',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Portal Publikasi',
                'instansi' => 'BPS',
                'url' => 'https://portalpublikasi.bps.go.id/',
                'description_link' => 'Portal Publikasi',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Mutasi Pegawai',
                'instansi' => 'BPS',
                'url' => 'https://sdm.bps.go.id/siimut',
                'description_link' => 'Sistem Mutasi Pegawai',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Pengolahan Data',
                'instansi' => 'BPS',
                'url' => 'https://query.web.bps.go.id/',
                'description_link' => 'Sistem Pengolahan Data',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Modul Penerimaan Negara',
                'instansi' => 'Kemenkeu',
                'url' => 'https://mpn.kemenkeu.go.id/new/login',
                'description_link' => 'Modul Penerimaan Negara',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'CMSBRI',
                'instansi' => 'BRI',
                'url' => 'https://ibank.bri.co.id/cms/',
                'description_link' => 'Cash Management System BRI',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Virtual Account Dashboard',
                'instansi' => 'BRI',
                'url' => 'https://brivirtualdebit.id/',
                'description_link' => 'Dashboard VA Cash Management System BRI',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Pengendalian Internal',
                'instansi' => 'BPS',
                'url' => 'https://spi.bps.go.id/v2/app/satker/spi',
                'description_link' => 'Sistem Pengendalian Internal',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SIMAN V2',
                'instansi' => '',
                'url' => 'https://siman.kemenkeu.go.id/',
                'description_link' => 'Sistem Informasi Manajemen Aset Negara',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Git BPS',
                'instansi' => '',
                'url' => 'https://git.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Prakom',
                'instansi' => '',
                'url' => 'https://prakom.bps.go.id',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Adobe BPS 2024',
                'instansi' => '',
                'url' => 'https://linktr.ee/AdobeBPS2024',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengolahan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Free Barcode Generator',
                'instansi' => '',
                'url' => 'https://www.free-barcode-generator.net/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pegawai Teladan',
                'instansi' => '',
                'url' => 'https://simpeg.bps.go.id/pegawai-teladan',
                'description_link' => '',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Akses BPS',
                'instansi' => '',
                'url' => 'https://akses.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'E-SAKIP Reviu',
                'instansi' => '',
                'url' => 'https://esr.menpan.go.id',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'IPD',
                'instansi' => '',
                'url' => 'https://ipd.bps.go.id/SiPW/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Monev PPID',
                'instansi' => '',
                'url' => 'https://emonev.kisb.sumbarprov.go.id/#top',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Simaspaten',
                'instansi' => '',
                'url' => 'https://simaspaten.kemenkeu.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Simdasi',
                'instansi' => '',
                'url' => 'https://simdasi.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Solok Kota',
                'instansi' => '',
                'url' => 'https://solokkota.bps.go.id/backend/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Webdash',
                'instansi' => '',
                'url' => 'https://webdash.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengolahan',
                'instansi' => '',
                'url' => 'https://pengolahan.bps.go.id/sosial/manajsusenas_rls',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Perpustakaan',
                'instansi' => '',
                'url' => 'https://perpustakaan.bps.go.id/digilib/admin/login',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Perpustakaan',
                'instansi' => '',
                'url' => 'https://perpustakaan.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'PPID',
                'instansi' => '',
                'url' => 'https://ppid.bps.go.id/?mfd=1372',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sippn',
                'instansi' => '',
                'url' => 'https://sippn.menpan.go.id/webcontrol/login',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Indah',
                'instansi' => '',
                'url' => 'https://indah.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Romantik',
                'instansi' => '',
                'url' => 'https://romantik.web.bps.go.id/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sirusa',
                'instansi' => '',
                'url' => 'https://sirusa.bps.go.id/sirusa/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Wilkerstat',
                'instansi' => '',
                'url' => 'https://wilkerstat.bps.go.id/public/login',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
        ];

        foreach ($links as $link) {
            Link::create($link);
        }
    }
}
