<?php

namespace Database\Seeders;

use App\Models\Link;
use App\Models\User;
use App\Models\Section;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LinksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $links = [
            [
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'link_name' => 'Website BPS RI',
                'instansi' => 'BPS',
                'url' => 'https://bps.go.id',
                'description_link' => 'Website Badan Pusat Statistik Republik Indonesia yang memuat data dan publikasi yang dirilis oleh BPS',
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'link_name' => 'Survey Management-Fasih SM',
                'instansi' => 'BPS',
                'url' => 'https://fasih-sm.bps.go.id/',
                'description_link' => 'Aplikasi berbasis web yang digunakan untuk melakukan pendataan menggunakan moda CAPI',
                'vpn' => true,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'link_name' => 'Website BPS Kota Solok',
                'instansi' => 'BPS',
                'url' => 'https://solokkota.bps.go.id',
                'description_link' => 'Website Badan Pusat Statistik Kota Solok yang memuat data dan publikasi yang dirilis oleh BPS',
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'section_id' => Section::where('section_name', 'Umum')->first()->id,
                'link_name' => 'E-learning Warkop BPS',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://lms.bps.go.id',
                'description_link' => 'E-learning warkop BPS merupakan platform yang menyediakan berbagai menu pembelajaran yang dapat dipilih oleh pengguna',
                'vpn' => false,
                'status' => 'Approved',
                'note' => null,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Pengolahan Survei/Sensus',
                'instansi' => 'BPS',
                'url' => 'https://webapps.bps.go.id/olah/seruti/login',
                'description_link' => 'Aplikasi berbasis web yang digunakan untuk melakukan entri data Susenas Seruti ',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengolahan Survei/Sensus')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Sistem Aplikasi Keuangan Tingkat Instansi (SAKTI)',
                'instansi' => 'Kemenkeu',
                'url' => 'https://sakti.kemenkeu.go.id/',
                'description_link' => 'Aplikasi berbasis web yang digunakan untuk pengelolaan keuangan (operator, bendahara, ppk, kpa)',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelolaan Keuangan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'OM-SPAN (Online Monitoring SPAN)',
                'instansi' => 'Kemenkeu',
                'url' => 'https://spanint.kemenkeu.go.id/',
                'description_link' => 'Aplikasi Berbasis Web Yang Dapat Di Akses Melalui Jaringan Internet Dan Internet Yang Digunakan Untuk Melakukan Monitoring Transaksi SPAN Dan Menyajikan Reporting Sesuai Kebutuhan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelolaan Keuangan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Sistem Aplikasi Terpadu DJA (SatuDJA)',
                'instansi' => 'Kemenkeu',
                'url' => 'https://satudja.kemenkeu.go.id/',
                'description_link' => 'sistem yang mengintegrasikan seluruh sistem informasi dan sistem aplikasi yang dihasilkan oleh DJA',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelolaan Keuangan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'BOS (Back Office Selindo)',
                'instansi' => 'BPS',
                'url' => 'https://backoffice.bps.go.id',
                'description_link' => 'BOS merupakan sistem informasi yang terintegrasi yang terdiri dari Manajemen Anggaran, Keuangan, Belanja, Pengadaan, Kepegawaian yang secara simultan berjalan di tingkat Pusat dan Daerah',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengelolaan Keuangan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Email BPS-Zimbra',
                'instansi' => 'BPS',
                'url' => 'https://mailhost.bps.go.id/',
                'description_link' => 'Aplikasi mail server untuk memanajemen email sehari-hari Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Pendidikan dan Pelatihan',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://pusdiklat.bps.go.id/',
                'description_link' => 'Website Pendidikan dan Pelatihan Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pendidikan & Pelatihan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Monitoring Sensus dan Survey',
                'instansi' => 'BPS',
                'url' => 'https://webmonitoring.bps.go.id/',
                'description_link' => 'Monitoring Pelaksanaan Pendataan, Monitoring Kualitas dan Monitoring Pengolahan Data Kegiatan Sensus dan Survey',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)',
                'instansi' => 'LKPP',
                'url' => 'https://sirup.lkpp.go.id/sirup/loginctr/index',
                'description_link' => 'Aplikasi Sistem Informasi Rencana Umum Pengadaan berbasis Web (Web based) yang fungsinya sebagai sarana atau alat untuk mengumumkan RUP',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengadaan Barang dan Jasa')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'LPSE Badan Pusat Statistik',
                'instansi' => 'BPS',
                'url' => 'https://lpse.bps.go.id/',
                'description_link' => 'Aplikasi untuk memfasilitasi pelaksanaan Pengadaan Barang/Jasa secara elektronik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengadaan Barang dan Jasa')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Rekomendasi Kegiatan Statistik',
                'instansi' => 'BPS',
                'url' => 'https://romantik.web.bps.go.id/',
                'description_link' => 'Layanan bagi instansi pemerintah untuk mendapatkan rekomendasi penyelenggaraan kegiatan statistik sektoral dari BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'PST BPS',
                'instansi' => 'BPS',
                'url' => 'https://pst.bps.go.id/login',
                'description_link' => 'Website yang berisi layanan yang disediakan oleh Badan Pusat Statistik',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => User::where('role', 'admin')->first()->id,
            ],
            [
                'link_name' => 'Dashboard Survei/Sensus',
                'instansi' => 'BPS',
                'url' => 'https://dashboard.bps.go.id/',
                'description_link' => 'Website yang berisi dashboard berbagai kegiatan survei/sensus dari berbagai tim seperti sosial, produksi, distribusi, dll',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Dashboard Fasih-SM',
                'instansi' => 'BPS',
                'url' => 'https://fasih-dashboard.bps.go.id/login/',
                'description_link' => 'Website yang berisi dashboard berbagai kegiatan survei/sensus yang menggunakan Fasih-SM',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'E-Learning BPS',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://elearning.bps.go.id/',
                'description_link' => 'Website yang ditujukan untuk media pembelajaran dan pelatihan jarak jauh',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pendidikan & Pelatihan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Komuniti Pegawai',
                'instansi' => 'BPS',
                'url' => 'https://community.bps.go.id/',
                'description_link' => 'Website yang berisikan struktur organisasi BPS, informasi pegawai, dan berita-berita BPS',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Manajemen Mitra',
                'instansi' => 'BPS',
                'url' => 'https://manajemen-mitra.bps.go.id/',
                'description_link' => 'Aplikasi Pengelolaan Mitra Kegiatan Sensus dan Survei Badan Pusat Statistik',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pendidikan & Pelatihan',
                'instansi' => 'Pusdiklat BPS',
                'url' => 'https://simdiklat.web.bps.go.id/',
                'description_link' => 'Sistem Informasi Manajemen Pendidikan dan Pelatihan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pendidikan & Pelatihan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengelolaan Dokumen',
                'instansi' => 'BPS',
                'url' => 'https://sipmen.bps.go.id/',
                'description_link' => 'Sistem Informasi Pengelolaan Dokumen',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Data Spasial',
                'instansi' => 'BPS',
                'url' => 'https://dataspasial.bps.go.id/index/',
                'description_link' => 'Sistem Informasi DATASPASIAL merupakan sistem informasi yang mengintegrasikan tiga sistem informasi yakni SIDIGIT, SIPETA, dan FORUM',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pemetaan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'MFD Online',
                'instansi' => 'BPS',
                'url' => 'https://frs.bps.go.id/area/login',
                'description_link' => 'Sistem pemutakhiran Master Wilayah dan Wilayah Kerja Statistik Memelihara hierarki perubahan wilayah yang dibutuhkan untuk bridging wilayah',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pemetaan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Quality Gate',
                'instansi' => 'BPS',
                'url' => 'https://frs.bps.go.id/area/login',
                'description_link' => 'Aplikasi digunakan untuk meningkatkan kualitas proses statistik dan mengukur serta memantau kualitas secara real time di titik-titik strategis',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Laporan Keuangan',
                'instansi' => 'Kemenkeu',
                'url' => 'https://akuntansi.bps.go.id/ecalkv2/web/site/login',
                'description_link' => 'Penyusun Laporan Keuangan Satker',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelolaan Keuangan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Layanan Online Kementerian Keuangan',
                'instansi' => 'Kemenkeu',
                'url' => 'https://spanint.kemenkeu.go.id/spanint/latest/app/',
                'description_link' => 'Monitoring Transaksi SPAN',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Digit Kemenkeu',
                'instansi' => 'Kemenkeu',
                'url' => 'https://digit.kemenkeu.go.id/login#/',
                'description_link' => 'Akses Antar Layanan Digital Dirjen Perbendaharaan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pajak',
                'instansi' => 'Kemenkeu',
                'url' => 'https://djponline.pajak.go.id/account/login',
                'description_link' => 'Pembuatan Billing Setor dan Pelaporan Pajak',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Monsakti Kemenkeu',
                'instansi' => 'Kemenkeu',
                'url' => 'https://monsakti.kemenkeu.go.id/dist/app/',
                'description_link' => 'Monitoring Sistem Aplikasi Keuangan oleh Pengguna Aplikasi Sakti',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Arsip Pegawai',
                'instansi' => 'BPS',
                'url' => 'https://simpeg.bps.go.id',
                'description_link' => 'Sistem Informasi Kepegawaian',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengajuan Cuti',
                'instansi' => 'BPS',
                'url' => 'https://sipecut.bps.go.id',
                'description_link' => 'Sistem Informasi Pengambilan Cuti',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Kippapp',
                'instansi' => 'BPS',
                'url' => 'https://webapps.bps.go.id/kipapp',
                'description_link' => 'KiPApp merupakan aplikasi berbasis web untuk mendukung penyelenggaraan Pengelolaan Kinerja ASN di lingkungan Badan Pusat Statistik',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Magang Mahasiswa STIS',
                'instansi' => 'STIS',
                'url' => 'https://magang.stis.ac.id/',
                'description_link' => 'Aplikasi yang digunakan untuk monitoring presensi dan kegiatan magang mahasiswa STIS',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Portal Publikasi',
                'instansi' => 'BPS',
                'url' => 'https://portalpublikasi.bps.go.id/',
                'description_link' => 'Website yang digunakan untuk mengelola publikasi ARC dan Non-ARC BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengajuan Pindah',
                'instansi' => 'BPS',
                'url' => 'https://sdm.bps.go.id/siimut',
                'description_link' => 'Sistem Informasi Layanan Mutasi Pegawai',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Tunjangan Kinerja
',
                'instansi' => 'BPS',
                'url' => 'https://tkonline.bps.go.id/',
                'description_link' => 'Website yang digunakan untuk entri tunjangan kinerja pegawai',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Query Survei/Sensus',
                'instansi' => 'BPS',
                'url' => 'https://query.web.bps.go.id/',
                'description_link' => 'Website yang digunakan untuk pengecekan data hasil olah ST2023',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Approval Sampel Sakernas',
                'instansi' => 'BPS',
                'url' => 'https://pengolahan.bps.go.id/sosial/manajsakernas_rls/site/index',
                'description_link' => 'Website yang digunakan untuk approval NKS kegiatan Sakernas',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengolahan Survei/Sensus')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Modul Penerimaan Negara',
                'instansi' => 'Kemenkeu',
                'url' => 'https://mpn.kemenkeu.go.id/new/login',
                'description_link' => 'Modul Pembuatan Billing Penerimaan Negara',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'CMSBRI',
                'instansi' => 'BRI',
                'url' => 'https://ibank.bri.co.id/cms/',
                'description_link' => 'Cash Management System BRI',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Virtual Account Dashboard',
                'instansi' => 'BRI',
                'url' => 'https://brivirtualdebit.id/',
                'description_link' => 'Dashboard VA Cash Management System BRI',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SPI Online',
                'instansi' => 'BPS',
                'url' => 'https://spi.bps.go.id/v2/app/satker/spi',
                'description_link' => 'Sistem Pengendalian Internal',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SIMAN V2',
                'instansi' => 'Kemenkeu',
                'url' => 'https://siman.kemenkeu.go.id/',
                'description_link' => 'Sistem Informasi Manajemen Aset Negara',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelolaan Barang Milik Negara')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Git BPS',
                'instansi' => '',
                'url' => 'https://git.bps.go.id/',
                'description_link' => 'Website yang digunakan untuk pelaporan berbagai permasalahan kegiatan survei/sensus',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengolahan Survei/Sensus')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Kanal Prakom',
                'instansi' => '',
                'url' => 'https://prakom.bps.go.id',
                'description_link' => 'Website yang dibuat untuk pranata komputer se-Indonesia dalam memahami juknis, mengarsipkan administrasi kegiatan pranata komputer (logbook), serta pengajuan penilaian (laporan kegiatan)',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Adobe BPS',
                'instansi' => 'BPS',
                'url' => 'https://linktr.ee/AdobeBPS2024',
                'description_link' => 'Website terkait penggunaan adobe seperti laporan penggunaan, BAST, dll',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Barcode Generator',
                'instansi' => 'Lainnya',
                'url' => 'https://www.free-barcode-generator.net/',
                'description_link' => '',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'IST (Insan Statistik Teladan)',
                'instansi' => 'BPS',
                'url' => 'https://simpeg.bps.go.id/pegawai-teladan',
                'description_link' => 'Website yang digunakan untuk pemilihan IST',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'VPN BPS',
                'instansi' => 'BPS',
                'url' => 'https://akses.bps.go.id/',
                'description_link' => 'Digunakan untuk koneksi VPN BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'TI')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'E-SAKIP Reviu',
                'instansi' => 'Kemenpan',
                'url' => 'https://esr.menpan.go.id',
                'description_link' => 'E-SAKIP Reviu',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SIPW',
                'instansi' => '',
                'url' => 'https://ipd.bps.go.id/SiPW/',
                'description_link' => 'Sistem Informasi Pemutakhiran Wilkerstat untuk mendukung pendataan ST2023',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pemetaan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Emonev',
                'instansi' => '',
                'url' => 'https://emonev.kisb.sumbarprov.go.id/#top',
                'description_link' => 'Monev PPID',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Kepegawaian')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Simaspaten',
                'instansi' => 'Kemenkeu',
                'url' => 'https://simaspaten.kemenkeu.go.id/',
                'description_link' => 'Sistem Informasi Penilaian Kompetensi bagi PPK dan PPSPM',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pengelola Anggaran')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Simdasi',
                'instansi' => 'BPS',
                'url' => 'https://simdasi.bps.go.id/',
                'description_link' => 'Sistem Informasi Manajemen Data Statistik Terintegrasi',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Update Website',
                'instansi' => 'BPS',
                'url' => 'https://solokkota.bps.go.id/backend/',
                'description_link' => 'Website yang digunakan untuk update tabel atau data website',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Dashboard Website',
                'instansi' => 'BPS',
                'url' => 'https://webdash.bps.go.id/',
                'description_link' => 'Dashboard yang berisikan statisitik atau laporan terkait dengan website BPS',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengolahan',
                'instansi' => 'BPS',
                'url' => 'https://pengolahan.bps.go.id/sosial/manajsusenas_rls',
                'description_link' => 'Website yang digunakan untuk approval NKS kegiatan Susenas',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengolahan Survei/Sensus')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Perpustakaan',
                'instansi' => 'BPS',
                'url' => 'https://perpustakaan.bps.go.id/digilib/admin/login',
                'description_link' => 'Dashboard Admin Perpustakaan BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Portal PPID',
                'instansi' => 'BPS',
                'url' => 'https://ppid.bps.go.id/?mfd=1372',
                'description_link' => 'Portal PPID Badan Pusat Statistik Kota Solok',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'SIPP Menpan',
                'instansi' => 'Kemenpan',
                'url' => 'https://sippn.menpan.go.id/webcontrol/login',
                'description_link' => 'Sistem Informasi Pelayanan Publik Menpan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Indonesia Data Hub',
                'instansi' => 'BPS',
                'url' => 'https://indah.bps.go.id/',
                'description_link' => 'Indonesia Data Hub merupakan one stop collaboration platform yang bertujuan untuk meningkatkan literasi data dan value of statistics serta mendukung interoperabilitas data dan kolaborasi eksplorasi terhadap data',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengajuan Rekomendasi Statistik',
                'instansi' => 'BPS',
                'url' => 'https://romantik.web.bps.go.id/',
                'description_link' => 'Layanan bagi instansi pemerintah untuk mendapatkan rekomendasi penyelenggaraan kegiatan statistik sektoral dari BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'Pelayanan Statistik Terpadu (PST)')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Sistem Informasi Rujukan Statistik',
                'instansi' => 'BPS',
                'url' => 'https://sirusa.bps.go.id/sirusa/',
                'description_link' => 'SIRuSa sebagai suatu website yang menyediakan informasi metadata kegiatan statistik yang ada di Indonesia',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Diseminasi Statistik')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Wilkerstat',
                'instansi' => 'BPS',
                'url' => 'https://wilkerstat.bps.go.id/public/login',
                'description_link' => 'Website Wilayah Kerja Statistik yang memuat data geotagging kegiatan survei/sensus',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pemetaan')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'BPS Shorten URL',
                'instansi' => 'BPS',
                'url' => 'https://s.bps.go.id/',
                'description_link' => 'Website yang digunakan untuk perpendek link agar mudah diingat. Berbagi link dengan pegawai lain menjadi lebih menyenangkan',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'TI')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Drive BPS',
                'instansi' => 'BPS',
                'url' => 'https://drive.bps.go.id/login',
                'description_link' => 'Website yang digunakan untuk penyimpanan file yang disediakan oleh BPS',
                'vpn' => false,
                'section_id' => Section::where('section_name', 'TI')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Survei Kebutuhan Data',
                'instansi' => 'BPS',
                'url' => 'https://skd.bps.go.id/2024/',
                'description_link' => 'Website Survei Kebutuhan Data yang diselenggarakan oleh BPS Setiap tahunnya',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Sensus/Survei')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
            [
                'link_name' => 'Pengolahan Survei Pariwisata',
                'instansi' => 'BPS',
                'url' => 'https://webentry.bps.go.id/pariwisata/login',
                'description_link' => 'Website yang digunakan untuk Pengolahan Survei Pariwisata',
                'vpn' => true,
                'section_id' => Section::where('section_name', 'Pengolahan Survei/Sensus')->first()->id,
                'submitted_by' => User::where('role', 'admin')->first()->id,
                'approved_by' => null,
                'status' => 'Approved',
                'note' => null,
            ],
        ];

        foreach ($links as $link) {
            Link::create($link);
        }
    }
}
